name: Run Python program

on:
  workflow_dispatch:   # разрешает запуск кнопкой

jobs:
  run-program:
    runs-on: ubuntu-latest

    steps:
      - name: Скачать код
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Запустить программу
        run: python main.py
